### ISSUE TITLE
Helping

### ISSUE THREAD

**Issue by yungtechboy1** [Comedyman937/MultiversePE#4]
Hey Man, Im a Coder, Web Developer, and I also run my own hosting company.
I would lover to help out on this project!

**Comment by 64FF00** [comment]
:+1:

**Comment by Comedyman937** [comment]
You can make pull requests ;)

**Comment by yungtechboy1** [comment]
Sorry, Wrong Project lol
Could I help with the Bootpanel
@Comedyman937

**Comment by Comedyman937** [comment]
Absolutely.  Please make pull requests to start and after you have shown contribution you'll be added to the organization

**Comment by yungtechboy1** [comment]
Ok Thanks
